name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use latest v3 if possible

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # v2 is newer
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to AWS
        run: |
          # Replace this with your actual deployment script
          echo "Deploying your app..."
